/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsViewingJujutsuDiffsInNeovimRouteImport } from './routes/posts/viewing-jujutsu-diffs-in-neovim'
import { Route as PostsTreesitterLanguageInjectionsRouteImport } from './routes/posts/treesitter-language-injections'
import { Route as PostsTreesitterCodeBlocksRouteImport } from './routes/posts/treesitter-code-blocks'
import { Route as ProjectsFumeExtractorIndexRouteImport } from './routes/projects/fume-extractor/index'
import { Route as ProjectsCartographerIndexRouteImport } from './routes/projects/cartographer/index'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PostsViewingJujutsuDiffsInNeovimRoute =
  PostsViewingJujutsuDiffsInNeovimRouteImport.update({
    id: '/viewing-jujutsu-diffs-in-neovim',
    path: '/viewing-jujutsu-diffs-in-neovim',
    getParentRoute: () => PostsRoute,
  } as any)
const PostsTreesitterLanguageInjectionsRoute =
  PostsTreesitterLanguageInjectionsRouteImport.update({
    id: '/treesitter-language-injections',
    path: '/treesitter-language-injections',
    getParentRoute: () => PostsRoute,
  } as any)
const PostsTreesitterCodeBlocksRoute =
  PostsTreesitterCodeBlocksRouteImport.update({
    id: '/treesitter-code-blocks',
    path: '/treesitter-code-blocks',
    getParentRoute: () => PostsRoute,
  } as any)
const ProjectsFumeExtractorIndexRoute =
  ProjectsFumeExtractorIndexRouteImport.update({
    id: '/fume-extractor/',
    path: '/fume-extractor/',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsCartographerIndexRoute =
  ProjectsCartographerIndexRouteImport.update({
    id: '/cartographer/',
    path: '/cartographer/',
    getParentRoute: () => ProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/posts/treesitter-code-blocks': typeof PostsTreesitterCodeBlocksRoute
  '/posts/treesitter-language-injections': typeof PostsTreesitterLanguageInjectionsRoute
  '/posts/viewing-jujutsu-diffs-in-neovim': typeof PostsViewingJujutsuDiffsInNeovimRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/cartographer': typeof ProjectsCartographerIndexRoute
  '/projects/fume-extractor': typeof ProjectsFumeExtractorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/treesitter-code-blocks': typeof PostsTreesitterCodeBlocksRoute
  '/posts/treesitter-language-injections': typeof PostsTreesitterLanguageInjectionsRoute
  '/posts/viewing-jujutsu-diffs-in-neovim': typeof PostsViewingJujutsuDiffsInNeovimRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/cartographer': typeof ProjectsCartographerIndexRoute
  '/projects/fume-extractor': typeof ProjectsFumeExtractorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/posts/treesitter-code-blocks': typeof PostsTreesitterCodeBlocksRoute
  '/posts/treesitter-language-injections': typeof PostsTreesitterLanguageInjectionsRoute
  '/posts/viewing-jujutsu-diffs-in-neovim': typeof PostsViewingJujutsuDiffsInNeovimRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/cartographer/': typeof ProjectsCartographerIndexRoute
  '/projects/fume-extractor/': typeof ProjectsFumeExtractorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/projects'
    | '/posts/treesitter-code-blocks'
    | '/posts/treesitter-language-injections'
    | '/posts/viewing-jujutsu-diffs-in-neovim'
    | '/posts/'
    | '/projects/'
    | '/projects/cartographer'
    | '/projects/fume-extractor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/treesitter-code-blocks'
    | '/posts/treesitter-language-injections'
    | '/posts/viewing-jujutsu-diffs-in-neovim'
    | '/posts'
    | '/projects'
    | '/projects/cartographer'
    | '/projects/fume-extractor'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/projects'
    | '/posts/treesitter-code-blocks'
    | '/posts/treesitter-language-injections'
    | '/posts/viewing-jujutsu-diffs-in-neovim'
    | '/posts/'
    | '/projects/'
    | '/projects/cartographer/'
    | '/projects/fume-extractor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/viewing-jujutsu-diffs-in-neovim': {
      id: '/posts/viewing-jujutsu-diffs-in-neovim'
      path: '/viewing-jujutsu-diffs-in-neovim'
      fullPath: '/posts/viewing-jujutsu-diffs-in-neovim'
      preLoaderRoute: typeof PostsViewingJujutsuDiffsInNeovimRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/treesitter-language-injections': {
      id: '/posts/treesitter-language-injections'
      path: '/treesitter-language-injections'
      fullPath: '/posts/treesitter-language-injections'
      preLoaderRoute: typeof PostsTreesitterLanguageInjectionsRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/treesitter-code-blocks': {
      id: '/posts/treesitter-code-blocks'
      path: '/treesitter-code-blocks'
      fullPath: '/posts/treesitter-code-blocks'
      preLoaderRoute: typeof PostsTreesitterCodeBlocksRouteImport
      parentRoute: typeof PostsRoute
    }
    '/projects/fume-extractor/': {
      id: '/projects/fume-extractor/'
      path: '/fume-extractor'
      fullPath: '/projects/fume-extractor'
      preLoaderRoute: typeof ProjectsFumeExtractorIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/cartographer/': {
      id: '/projects/cartographer/'
      path: '/cartographer'
      fullPath: '/projects/cartographer'
      preLoaderRoute: typeof ProjectsCartographerIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsTreesitterCodeBlocksRoute: typeof PostsTreesitterCodeBlocksRoute
  PostsTreesitterLanguageInjectionsRoute: typeof PostsTreesitterLanguageInjectionsRoute
  PostsViewingJujutsuDiffsInNeovimRoute: typeof PostsViewingJujutsuDiffsInNeovimRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsTreesitterCodeBlocksRoute: PostsTreesitterCodeBlocksRoute,
  PostsTreesitterLanguageInjectionsRoute:
    PostsTreesitterLanguageInjectionsRoute,
  PostsViewingJujutsuDiffsInNeovimRoute: PostsViewingJujutsuDiffsInNeovimRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsCartographerIndexRoute: typeof ProjectsCartographerIndexRoute
  ProjectsFumeExtractorIndexRoute: typeof ProjectsFumeExtractorIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsCartographerIndexRoute: ProjectsCartographerIndexRoute,
  ProjectsFumeExtractorIndexRoute: ProjectsFumeExtractorIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRoute: PostsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
